server:
  port: 8081

spring:
  application:
    name: bank-accounts-api
  
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/bank_db?currentSchema=bank}
    username: ${SPRING_R2DBC_USERNAME:bank_user}
    password: ${SPRING_R2DBC_PASSWORD:bank_password}
    
  liquibase:
    enabled: ${SPRING_LIQUIBASE_ENABLED:true}
    change-log: classpath:/db/changelog/db.changelog-master.xml

logging:
  level:
    com.pichincha.dm.bank.accounts: DEBUG
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
